### ISSUE TITLE
请问怎么生成正面图？

### ISSUE THREAD

**Issue by zealpane** [GuiRitter/NormalMapMaker#1]
你好，我看程序里面生成的是顶部图，请问怎么样能生成正面图？

**Comment by GuiRitter** [comment]
I'm sorry, but I had to use Google Translate to read what you wrote, but I couldn't understand it. Can you write your question differently? I'll use Google Translate to translate this comment as well.

对不起，但是我不得不使用Google翻译来阅读你写的内容，但是我无法理解。 你可以写出你的问题吗？ 我也会使用Google翻译来翻译此评论。

**Comment by zealpane** [comment]
嗯，不好意思，非常感谢你的这个项目解决了我目前遇到的一个问题。
我现在也是用google翻译来翻译的这段话，不知道你是否能理解。
请问怎么改变stl文件生成缩略图的视角，不是从顶部，而是从正面。

Well, sorry, thank you very much for this project to solve a problem I am currently experiencing.
I am now using google translation to translate this paragraph, do not know if you can understand.
Ask how to change the stl file to generate thumbnails from the perspective, not from the top, but from the front.

**Comment by GuiRitter** [comment]
I can understand you much better now. It's simple: use [Blender](https://en.wikipedia.org/wiki/Blender_(software)).

1. Load the STL file in Blender.
2. Rotate your model such that the side you want to see is facing the positive side of the Z axis.
3. Export your STL file and use it in my program.

I hope you can understand my instructions and solve your issues.

我现在可以理解你好多了 很简单：使用[Blender](https://zh.wikipedia.org/wiki/Blender_(software))。

1. 在Blender中加载STL文件。
2. 旋转模型，使您想要看到的一面正对着Z轴的正面。
3. 导出您的STL文件并在我的程序中使用它。

希望你能理解我的指示并解决你的问题。

**Comment by zealpane** [comment]
thank you very much

**Comment by GuiRitter** [comment]
You're welcome!
